/**
 * Root DataModel names probed by `listSolutions` when enumerating ER solutions.
 *
 * F&O exposes NO server-side "list all solutions" operation: the
 * `ERConfigurationListService` catalog contains only
 * `getFormatSolutionsSubHierarchy` (requires a concrete `_parentSolutionName`;
 * an empty/null name returns 0 rows) and
 * `getCountOfConfigurationsByCountryCode`. There are also no OData entities
 * for ER configurations. Enumeration therefore works by probing known root
 * DataModel names in parallel — each hit returns its whole derived sub-tree.
 *
 * Models missing from this list can be supplied at call time via
 * `options.extraRoots` (the UI persists user-added roots per connection).
 */
export const DEFAULT_SEED_MODELS: readonly string[] = [
  'Tax declaration model',
  'Payment model',
  'Invoice model',
  'Audit file model',
  'Bank statement model',
  'General ledger model',
  'Fixed asset model',
  'Purchase order model',
  'Sales order model',
  'Customer model',
  'Vendor model',
  'Intrastat model',
  // Additional root DataModels often present in F&O
  'Electronic messages',
  'EU Sales list',
  'Asset leasing',
  'Regulatory configuration',
  'Standard Audit File (SAF-T)',
  'Customs declaration model',
  'Cost accounting',
  'Fiscal documents',
  'Data exchange',
  'Financial dimensions',
  'Inventory management model',
  'Project model',
  'Budget model',
  'Ledger settlement model',
  'Electronic invoicing model',
  'Financial reporting model',
  'Cash flow forecasting model',
  'Credit management model',
  'Retail model',
  'Warehouse management model',
  'Supply chain model',
  'HR model',
  'Payroll model',
  'Transportation management model',
  'Expense management model',
  'Subscription billing model',
  'Revenue recognition model',
  'Withholding tax model',
  'Document routing model',
  'Advance holder model',
  'Currency revaluation model',
  'Rebate management model',
  'Global inventory accounting model',
  'MT940 Model',
  'Camt model',
  'ACA 1095B report model',
  'ACA 1095C report model',
  'Advanced bank reconciliation statement model',
  'Aging analysis of receivable payment model',
  'Aging and due amount analysis shared model',
  'Assets declarations model',
  'BAS model',
  'BLWI model',
  'Balance report model',
  'Bank Reconciliation Report Model',
  'Bank Statement Model for BAI2',
  'Benefit statement model',
  'Bill of lading model',
  'CODA model',
  'Cash Receipt Model',
  'Cash Register Model',
  'Cash receipts model',
  'Certificate of origin model',
  'Collection letter model',
  'Construction industry scheme model',
  'Course agenda model',
  'Customer invoice context model',
  'Customer invoice context model (FR)',
  'Customer invoicing model',
  'Customer prepayment invoice model',
  'Data export model',
  'Declaration 347 model',
  'Dutch XBRL integration model',
  'EEO-1 report model',
  'EU Sales list model',
  'Electronic Messages framework model',
  'Electronic ledger accounting model MX',
  'Electronic trial balance detail report model',
  'Financial reports model',
  'Fiscal journal model (IT)',
  'Fixed assets model',
  'GAF model (MY)',
  'GBT24589-2010 model',
  'GST Returns govt. model',
  'GST Returns model',
  'GoldenTax model',
  'Hungarian VAT reporting model',
  'INTERVAT model',
  'Import invoice context model',
  'Inventory journal model',
  'Invoice Model LATAM',
  'Invoice list model',
  'Invoice turnover report model',
  'Invoices Communication Model',
  'Italian intent letter telematic model',
  'Italian tax reports model',
  'JBA Payment model',
  'Letter of credit model',
  'Model for binary data pipeline',
  'Modello770 report (IT)',
  'OSHA 300A report model',
  'Order model',
  'Packing list model',
  'Payment check model',
  'Payment check model (TR)',
  'Payment check model LATAM',
  'Payment model (BR)',
  'Performance review model',
  'Positive pay model',
  'Production consumption variance report model',
  'Products turnover model',
  'Quotation model',
  'Reconciliation model',
  'Reminder model',
  'Response message model',
  'SIE export model',
  'SPED model',
  'Sales tax model',
  'Services fiscal document model',
  'Spanish VAT model',
  'Submitted document model',
  'Tax Calculation Data Model',
  'Tax Calculation Data Model (Brazil)',
  'Tax Calculation Data Model for ISV integration',
  'Tax Data Model',
  'Unique Certification model',
  'VAT declaration model',
  'VAT declaration model (RU)',
  'VETS report model',
  'Vendor invoice declaration model',
  'Vendor size category model',
  'Waybill model',
  'e-Ledger Model (TR)',
];

